=== helderdarocha/LearnXML/Lab_Aula_4/pessoa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="______"
    xmlns:pes="______">

    <element name="pessoas">
        <complexType>
            <sequence>
                <element ref="pes:pessoa" 
                            maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    
    <element name="pessoa">
        <complexType>
            <sequence>
                <element ref="pes:nome" />
            </sequence>
        </complexType>
    </element>
    
    <element name="nome" type="string" />

</schema>

=== helderdarocha/LearnXML/Lab_Aula_4/pessoas.xml
<?xml version="1.0" encoding="UTF-8"?>

<pessoas xmlns:xxx="http://www.w3.org/2001/XMLSchema-instance"
    xxx:schemaLocation="______ pessoa.xsd"
    xmlns="______">
    
    <pessoa>
        <nome>Charles Darwin</nome>
    </pessoa>
    <pessoa>
        <nome>Erich Gamma</nome> 
    </pessoa>
    <pessoa>
        <nome>John Vlissides</nome>
    </pessoa>
    <pessoa>
        <nome>Helm</nome>
    </pessoa>
    <pessoa>
        <nome>Johnson</nome>
    </pessoa>
    <pessoa>
        <nome>F. Scott Fitzgerald</nome>
    </pessoa>
</pessoas>
