=== helderdarocha/LearnXML/Lab_Aula_4/Rowsets_2_noNS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified">
  
  <xs:element name="Rowsets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Rowset"/>
      </xs:sequence>
      <xs:attribute name="DateCreated" use="required" type="xs:dateTime"/>
      <xs:attribute name="EndDate" use="required" type="xs:dateTime"/>
      <xs:attribute name="StartDate" use="required" type="xs:dateTime"/>
      <xs:attribute name="Version" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rowset">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Columns"/>
        <xs:element ref="Row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Columns">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Column"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Column">
    <xs:complexType>
      <xs:attribute name="Description" use="required" type="xs:NCName"/>
      <xs:attribute name="MaxRange" use="required" type="xs:integer"/>
      <xs:attribute name="MinRange" use="required" type="xs:integer"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="SQLDataType" use="required" type="xs:integer"/>
      <xs:attribute name="SourceColumn" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="DateTime"/>
        <xs:choice>
          <xs:sequence>
            <xs:element ref="MIN_CylTemp2"/>
            <xs:element ref="MAX_CylTemp2"/>
            <xs:element ref="AVG_CylTemp2"/>
          </xs:sequence>
          <xs:sequence>
            <xs:element ref="MIN_CylTemp4"/>
            <xs:element ref="MAX_CylTemp4"/>
            <xs:element ref="AVG_CylTemp4"/>
          </xs:sequence>
          <xs:sequence>
            <xs:element ref="MIN_CylTemp1"/>
            <xs:element ref="MAX_CylTemp1"/>
            <xs:element ref="AVG_CylTemp1"/>
          </xs:sequence>
          <xs:sequence>
            <xs:element ref="MIN_CylTemp3"/>
            <xs:element ref="MAX_CylTemp3"/>
            <xs:element ref="AVG_CylTemp3"/>
          </xs:sequence>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DateTime" type="xs:dateTime"/>
  <xs:element name="MIN_CylTemp2" type="xs:integer"/>
  <xs:element name="MAX_CylTemp2" type="xs:decimal"/>
  <xs:element name="AVG_CylTemp2" type="xs:decimal"/>
  <xs:element name="MIN_CylTemp4" type="xs:integer"/>
  <xs:element name="MAX_CylTemp4" type="xs:decimal"/>
  <xs:element name="AVG_CylTemp4" type="xs:decimal"/>
  <xs:element name="MIN_CylTemp1" type="xs:integer"/>
  <xs:element name="MAX_CylTemp1" type="xs:decimal"/>
  <xs:element name="AVG_CylTemp1" type="xs:decimal"/>
  <xs:element name="MIN_CylTemp3" type="xs:integer"/>
  <xs:element name="MAX_CylTemp3" type="xs:integer"/>
  <xs:element name="AVG_CylTemp3" type="xs:decimal"/>
</xs:schema>

=== helderdarocha/LearnXML/Lab_Aula_4/Rowsets_NoNS.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--DOCTYPE Rowsets SYSTEM "RowSets.dtd"-->

<Rowsets DateCreated="2010-12-07T13:29:09" 
    EndDate="2010-12-07T13:29:09" 
    StartDate="2010-12-07T12:29:09" 
    Version="12.0.4 Build(120)"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Rowsets_2_noNS.xsd">
    
    <Rowset>
        <Columns>
            <Column Description="DateTime" MaxRange="1" MinRange="0" Name="DateTime" SQLDataType="93" SourceColumn="DateTime"/>
            <Column Description="CylTemp1" MaxRange="200" MinRange="0" Name="MIN_CylTemp1" SQLDataType="8" SourceColumn="CylTemp1"/>
            <Column Description="CylTemp1" MaxRange="200" MinRange="0" Name="MAX_CylTemp1" SQLDataType="8" SourceColumn="CylTemp1"/>
            <Column Description="CylTemp1" MaxRange="200" MinRange="0" Name="AVG_CylTemp1" SQLDataType="8" SourceColumn="CylTemp1"/>
        </Columns>
        <Row>
            <DateTime>2010-12-07T13:29:09</DateTime>
            <MIN_CylTemp1>0</MIN_CylTemp1>
            <MAX_CylTemp1>140.255201535155</MAX_CylTemp1>
            <AVG_CylTemp1>65.783711343522</AVG_CylTemp1>
        </Row>
    </Rowset>
    <Rowset>
        <Columns>
            <Column Description="DateTime" MaxRange="1" MinRange="0" Name="DateTime" SQLDataType="93" SourceColumn="DateTime"/>
            <Column Description="CylTemp2" MaxRange="200" MinRange="0" Name="MIN_CylTemp2" SQLDataType="8" SourceColumn="CylTemp2"/>
            <Column Description="CylTemp2" MaxRange="200" MinRange="0" Name="MAX_CylTemp2" SQLDataType="8" SourceColumn="CylTemp2"/>
            <Column Description="CylTemp2" MaxRange="200" MinRange="0" Name="AVG_CylTemp2" SQLDataType="8" SourceColumn="CylTemp2"/>
        </Columns>
        <Row>
            <DateTime>2010-12-07T13:29:09</DateTime>
            <MIN_CylTemp2>0</MIN_CylTemp2>
            <MAX_CylTemp2>171.780374428865</MAX_CylTemp2>
            <AVG_CylTemp2>83.994636662206</AVG_CylTemp2>
        </Row>
    </Rowset>
    <Rowset>
        <Columns>
            <Column Description="DateTime" MaxRange="1" MinRange="0" Name="DateTime" SQLDataType="93" SourceColumn="DateTime"/>
            <Column Description="CylTemp3" MaxRange="200" MinRange="0" Name="MIN_CylTemp3" SQLDataType="8" SourceColumn="CylTemp3"/>
            <Column Description="CylTemp3" MaxRange="200" MinRange="0" Name="MAX_CylTemp3" SQLDataType="8" SourceColumn="CylTemp3"/>
            <Column Description="CylTemp3" MaxRange="200" MinRange="0" Name="AVG_CylTemp3" SQLDataType="8" SourceColumn="CylTemp3"/>
        </Columns>
        <Row>
            <DateTime>2010-12-07T13:29:09</DateTime>
            <MIN_CylTemp3>0</MIN_CylTemp3>
            <MAX_CylTemp3>200</MAX_CylTemp3>
            <AVG_CylTemp3>101.229388906706</AVG_CylTemp3>
        </Row>
    </Rowset>
    <Rowset>
        <Columns>
            <Column Description="DateTime" MaxRange="1" MinRange="0" Name="DateTime" SQLDataType="93" SourceColumn="DateTime"/>
            <Column Description="CylTemp4" MaxRange="200" MinRange="0" Name="MIN_CylTemp4" SQLDataType="8" SourceColumn="CylTemp4"/>
            <Column Description="CylTemp4" MaxRange="200" MinRange="0" Name="MAX_CylTemp4" SQLDataType="8" SourceColumn="CylTemp4"/>
            <Column Description="CylTemp4" MaxRange="200" MinRange="0" Name="AVG_CylTemp4" SQLDataType="8" SourceColumn="CylTemp4"/>
        </Columns>
        <Row>
            <DateTime>2010-12-07T13:29:09</DateTime>
            <MIN_CylTemp4>0</MIN_CylTemp4>
            <MAX_CylTemp4>146.145784934178</MAX_CylTemp4>
            <AVG_CylTemp4>61.266629917637</AVG_CylTemp4>
        </Row>
    </Rowset>
</Rowsets>

<!-- 

schemaLocation="namespace                    url_onde_esta_o_xsd
ns2                          ../outra_url
ns3                          file:///c/windows/esquemas/esquema.xsd
urn:frances                  http://www.francais.fr/schemas/frances.xsd
http://www.w3.org/1999/xhtml http://www.w3.org/xhtml/schemas/xhtml11.xsd
URI                          URL
http://www.x.com/livro.xsd   http://www.x.com/livro.xsd
uri:Rowsets-MII              RowSets.xsd"

xmlns="namespace"
xmlns:ns2="ns2"
xmlns:ns3="ns3"
xmlns:fr="urn:frances"
xmlns:html="http://www.w3.org/1999/xhtml"
xmlns:uri="URI"
xmlns:livro="http://www.x.com/livro.xsd"
xmlns:mii="uri:Rowsets-MII"

-->
