=== helderdarocha/LearnXML/Lab_Aula_3/biblioteca_4_notation.dtd
<!ELEMENT biblioteca (pessoa*, livro*) >

<!NOTATION brasileira SYSTEM "http://www.abl.org">
<!NOTATION argentina  SYSTEM "http://www.xyz.ar/libros">

<!ELEMENT pessoa (nome) >
<!ATTLIST pessoa tipo (autor | tradutor | editor) "autor"
                 id ID #REQUIRED
                 academia (brasileira | argentina) #IMPLIED>

<!ELEMENT nome (#PCDATA) >

<!ELEMENT livro     (titulo, idioma, assunto+, descricao) >
<!ATTLIST livro numero NMTOKEN #REQUIRED 
                data   NMTOKEN #REQUIRED 
                id ID #REQUIRED
                autorRef IDREFS #REQUIRED>

<!ELEMENT titulo    (#PCDATA) >

<!ELEMENT idioma    (#PCDATA) >
<!ATTLIST idioma codigo (pt | en | de | fr | es) #REQUIRED >

<!ELEMENT autor     (#PCDATA) >

<!ELEMENT assunto   (#PCDATA) >
<!ATTLIST assunto dewey NMTOKEN #REQUIRED >

<!ELEMENT termo     (#PCDATA) >

<!ELEMENT sinopse   (#PCDATA) >

<!ELEMENT descricao (#PCDATA | termo | sinopse)* >

=== helderdarocha/LearnXML/Lab_Aula_3/biblioteca_4_notation.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca SYSTEM "biblioteca_4_notation.dtd">

<biblioteca>
    <pessoa id="J344" academia="brasileira">
        <nome>Chico Buarque</nome>
    </pessoa>
    <pessoa id="J345" academia="argentina">
        <nome>Jorge Luis Borges</nome>
    </pessoa>
    
    <livro numero="5" data="2010-10-01" id="L.991" autorRef="J344">
        <titulo>Ficciones</titulo>
        <idioma codigo="es"></idioma>
        <assunto dewey="860">Literatura de Lingua Espanhola</assunto>
        <descricao></descricao>
    </livro>
    
</biblioteca>
