=== helderdarocha/LearnXML/Lab_Aula_3/livro.dtd
<!ELEMENT livro     (titulo, idioma, autor+, assunto+, descricao) >
<!ATTLIST livro numero CDATA #IMPLIED 
                data   CDATA #IMPLIED >

<!ELEMENT titulo    (#PCDATA) >

<!ELEMENT idioma    (#PCDATA) >
<!ATTLIST idioma codigo CDATA #IMPLIED >

<!ELEMENT autor     (#PCDATA) >

<!ELEMENT assunto   (#PCDATA) >
<!ATTLIST assunto dewey CDATA #IMPLIED >

<!ELEMENT termo     (#PCDATA) >

<!ELEMENT sinopse   (#PCDATA) >

<!ELEMENT descricao (#PCDATA | termo | sinopse)* >

=== helderdarocha/LearnXML/Lab_Aula_3/livro_1.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE livro SYSTEM "livro.dtd">
<livro numero="1" data="2010-12-08">
    <titulo>A Origem das Especies</titulo>
    <idioma codigo="pt" />
    <autor>Charles Darwin</autor>
    <assunto dewey="540">Biologia</assunto>
    <assunto dewey="542">Zoologia</assunto>
    <descricao>Este livro narra as descobertas do autor 
        e teorias sobre a origem e das especies
        com base em sua viagem pela<termo>America do Sul</termo>,
        principalmente nas <termo>Ilhas Galapagos</termo>.
        E a obra mais importante relacionada a <termo>teoria da
            evolucao</termo> das especies.
    </descricao>
</livro>

=== helderdarocha/LearnXML/Lab_Aula_3/livro_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livro SYSTEM "livro.dtd">
<livro>
    <titulo>Design Patterns</titulo>
    <idioma/>
    <autor>Erich Gamma</autor>
    <autor>John Vlissides</autor>
    <autor>Helm</autor>
    <autor>Johnson</autor>
    <assunto>Informatica: programacao</assunto>
    <descricao>Classico do padroes de design.</descricao>
</livro>

=== helderdarocha/LearnXML/Lab_Aula_3/livro_4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE livro SYSTEM "livro.dtd">
<livro numero="4" data="2010-09-20">
    <titulo>Contos da Era do Jazz</titulo>
    <idioma codigo="pt" />
    <autor>F. Scott Fitzgerald</autor>
    <assunto dewey="813">Ficcao dos Estados Unidos, Seculo XX</assunto>
    <descricao>Diversos contos do inicio do seculo XX (<termo>Era do Jazz</termo>). 
        <sinopse>Coloque aqui uma sinopse deste livro.</sinopse>
    </descricao>
</livro>
