=== helderdarocha/LearnXML/Exercicios_OLD/Parte_2_dtd/orbita.dtd
<!ELEMENT orbita (planeta?,planeta-anao*,(objeto*|asteroide*))>
<!ATTLIST orbita
  nome              CDATA   #IMPLIED
  raioMedUA         NMTOKEN #REQUIRED>

<!ELEMENT planeta (imagem*,satelite*)>
<!ATTLIST planeta
  categoria         CDATA   #IMPLIED
  afelioUA          NMTOKEN #REQUIRED
  anoDescobrimento  NMTOKEN #IMPLIED
  descobertoPor     CDATA   #IMPLIED
  diametrokm        NMTOKEN #REQUIRED
  id                NMTOKEN #REQUIRED
  inclinacaoAxial   NMTOKEN #REQUIRED
  massaKg           NMTOKEN #REQUIRED
  nome              CDATA   #REQUIRED
  perielioUA        NMTOKEN #REQUIRED
  periodoOrbitalD   NMTOKEN #REQUIRED
  periodoRotacaoSideralH NMTOKEN #REQUIRED>

<!ELEMENT planeta-anao (imagem*,satelite*)>
<!ATTLIST planeta-anao
  categoria         CDATA   #IMPLIED
  afelioUA          NMTOKEN #REQUIRED
  anoDescobrimento  NMTOKEN #IMPLIED
  descobertoPor     CDATA   #IMPLIED
  diametrokm        NMTOKEN #REQUIRED
  id                NMTOKEN #REQUIRED
  inclinacaoAxial   NMTOKEN #IMPLIED
  massaKg           NMTOKEN #REQUIRED
  nome              CDATA   #REQUIRED
  perielioUA        NMTOKEN #REQUIRED
  periodoOrbitalD   NMTOKEN #REQUIRED>

<!ELEMENT objeto (imagem*,satelite*)>
<!ATTLIST objeto
  categoria         CDATA   #IMPLIED
  afelioUA          NMTOKEN #REQUIRED
  anoDescobrimento  NMTOKEN #REQUIRED
  descobertoPor     CDATA   #REQUIRED
  diametrokm        NMTOKEN #REQUIRED
  id                NMTOKEN #REQUIRED
  massaKg           NMTOKEN #IMPLIED
  nome              CDATA   #REQUIRED
  perielioUA        NMTOKEN #REQUIRED
  periodoOrbitalD   NMTOKEN #REQUIRED>

<!ELEMENT asteroide (imagem*,satelite*)>
<!ATTLIST asteroide
  categoria         CDATA   #IMPLIED
  afelioUA          NMTOKEN #REQUIRED
  anoDescobrimento  NMTOKEN #IMPLIED
  descobertoPor     CDATA   #IMPLIED
  diametrokm        NMTOKEN #REQUIRED
  id                NMTOKEN #REQUIRED
  massaKg           NMTOKEN #IMPLIED
  nome              CDATA   #REQUIRED
  perielioUA        NMTOKEN #REQUIRED
  periodoOrbitalD   NMTOKEN #REQUIRED>

<!ELEMENT imagem EMPTY>
<!ATTLIST imagem
  href              NMTOKEN #REQUIRED
  height            NMTOKEN #IMPLIED
  width             NMTOKEN #IMPLIED
  type              CDATA   #IMPLIED>

<!ELEMENT satelite (imagem*, satelite*)>
<!ATTLIST satelite
  categoria         CDATA   #IMPLIED
  anoDescobrimento  NMTOKEN #IMPLIED
  descobertoPor     CDATA   #IMPLIED
  diametrokm        NMTOKEN #REQUIRED
  id                NMTOKEN #REQUIRED
  massaKg           NMTOKEN #IMPLIED
  nome              CDATA   #REQUIRED
  raioMedOrbitakm   NMTOKEN #REQUIRED>

=== helderdarocha/LearnXML/Exercicios_OLD/Parte_2_dtd/orbita_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orbita SYSTEM "orbita.dtd" >
<orbita raioMedUA="2.75" nome="Cinturão de Asteroides">
    <planeta-anao id="a1"  nome="Ceres"     diametrokm="952" perielioUA="2.547" afelioUA="2.996" periodoOrbitalD="1680" inclinacaoAxial="4" massaKg="9.3e20" anoDescobrimento="1801" descobertoPor="Guiseppe Piazzi" >
        <imagem href="ceres.jpg" />
    </planeta-anao>

      <asteroide id="a2"    nome="Pallas"     diametrokm="522" perielioUA="2.132" afelioUA="3.412" periodoOrbitalD="1686"   massaKg="2e20" anoDescobrimento="1802" descobertoPor="Heinrich Olbers" /> 
    <asteroide id="a3"    nome="Juno"       diametrokm="258" perielioUA="1.988" afelioUA="3.353" periodoOrbitalD="1595.4" anoDescobrimento="1804" descobertoPor="Karl Ludwig Harding" /> 
    <asteroide id="a4"    nome="Vesta"      diametrokm="529" perielioUA="2.151" afelioUA="5.572" periodoOrbitalD="1325.2" massaKg="2.6e20" anoDescobrimento="1807" descobertoPor="Heinrich Olbers" />
    <asteroide id="a5"    nome="Astréia"    diametrokm="119" perielioUA="2.077" afelioUA="3.070" periodoOrbitalD="1507.7" anoDescobrimento="1903" descobertoPor="Karl Ludwig Hencke" />
    <asteroide id="a6"    nome="Hebe"       diametrokm="186" perielioUA="1.937" afelioUA="2.914" periodoOrbitalD="1379.8" anoDescobrimento="1847" descobertoPor="Karl Ludwig Hencke" /> 
    <asteroide id="a7"    nome="Iris"       diametrokm="213" perielioUA="1.833" afelioUA="2.937" periodoOrbitalD="1347.8" anoDescobrimento="1847" descobertoPor="John Russell Hind" /> 
    <asteroide id="a8"    nome="Flora"      diametrokm="128" perielioUA="1.858" afelioUA="2.546" periodoOrbitalD="1193"   anoDescobrimento="1903" descobertoPor="John Russell Hind" /> 
    <asteroide id="a9"    nome="Métis"      diametrokm="190" perielioUA="2.096" afelioUA="2.678" periodoOrbitalD="1346.8" anoDescobrimento="1848" descobertoPor="Andrew Graham" /> 
    <asteroide id="a10"   nome="Higiéia"    diametrokm="431" perielioUA="2.77"  afelioUA="3.507" periodoOrbitalD="2031"   anoDescobrimento="1849" descobertoPor="Annibale de Gasparis" /> 
    <asteroide id="a11"   nome="Parthenope" diametrokm="153" perielioUA="2.208" afelioUA="2.697" periodoOrbitalD="1402.9" anoDescobrimento="1850" descobertoPor="Annibale de Gasparis" />  
    <asteroide id="a12"   nome="Victoria"   diametrokm="113" perielioUA="1.819" afelioUA="2.849" periodoOrbitalD="1302.4" anoDescobrimento="1850" descobertoPor="John Russell Hind" /> 
    <asteroide id="a13"   nome="Egéria"     diametrokm="206" perielioUA="2.358" afelioUA="2.794" periodoOrbitalD="1510"   anoDescobrimento="1850" descobertoPor="Annibale de Gasparis" /> 
    <asteroide id="a14"   nome="Irene"      diametrokm="152" perielioUA="2.150" afelioUA="3.020" periodoOrbitalD="1518.2" anoDescobrimento="1851" descobertoPor="John Russell Hind" /> 
    <asteroide id="a15"   nome="Eunomia"    diametrokm="272" perielioUA="2.149" afelioUA="3.138" periodoOrbitalD="1569.7" anoDescobrimento="1851" descobertoPor="Annibale de Gasparis" /> 
    <asteroide id="a16"   nome="Psyque"     diametrokm="264" perielioUA="2.513" afelioUA="3.328" periodoOrbitalD="1823"   anoDescobrimento="1852" descobertoPor="Annibale de Gasparis" /> 
    <asteroide id="a17"   nome="Tétis"      diametrokm="90"  perielioUA="2.139" afelioUA="2.801" periodoOrbitalD="1418"   anoDescobrimento="1852" descobertoPor="Robert Luther " />
    <asteroide id="a18"   nome="Melpomene"  diametrokm="141" perielioUA="1.795" afelioUA="2.797" periodoOrbitalD="1270.6" anoDescobrimento="1852" descobertoPor="John Russell Hind" />
    <asteroide id="a19"   nome="Fortuna"    diametrokm="225" perielioUA="2.052" afelioUA="2.831" periodoOrbitalD="1393.4" anoDescobrimento="1852" descobertoPor="John Russell Hind" /> 
    <asteroide id="a20"   nome="Massália"   diametrokm="145" perielioUA="2.064" afelioUA="2.753" periodoOrbitalD="1365.3" anoDescobrimento="1852" descobertoPor="Annibale de Gasparis" />
    <asteroide id="a21"   nome="Lutécia"    diametrokm="100" perielioUA="2.036" afelioUA="2.834" periodoOrbitalD="1387.9" anoDescobrimento="1852" descobertoPor="Hermann Goldschmidt" />
    <asteroide id="a24"   nome="Temis"      diametrokm="198" perielioUA="2.719" afelioUA="3.539" periodoOrbitalD="2021"   anoDescobrimento="1853" descobertoPor="Annibale de Gasparis" />
    <asteroide id="a29"   nome="Anfritite"  diametrokm="212" perielioUA="2.369" afelioUA="2.739" periodoOrbitalD="1491"   anoDescobrimento="1854" descobertoPor="Albert Marth" /> 
    <asteroide id="a31"   nome="Eufrosine"  diametrokm="256" perielioUA="2.438" afelioUA="3.861" periodoOrbitalD="2041.6" anoDescobrimento="1854" descobertoPor="James Ferguson" /> 
    <asteroide id="a38"   nome="Leda"       diametrokm="116" perielioUA="2.328" afelioUA="3.159" periodoOrbitalD="1660"   anoDescobrimento="1856" descobertoPor="Jean Chacornac" />
    <asteroide id="a45"   nome="Eugênia"    diametrokm="213" perielioUA="2.497" afelioUA="2.943" periodoOrbitalD="1638.5" anoDescobrimento="1857" descobertoPor="Hermann Goldschmidt" >
        <satelite id="s1998.45.1" nome="Petit-Prince"      diametrokm="13"   raioMedOrbitakm="-1"  anoDescobrimento="1998" descobertoPor="Canada-France-Hawaii Telescope" />
        <satelite id="s2004.45.2" nome="S/2004 45 1"       diametrokm="6"    raioMedOrbitakm="-1"  anoDescobrimento="2007" descobertoPor="ESO" />
    </asteroide> 
    <asteroide id="a48"   nome="Doris"      diametrokm="222" perielioUA="2.877" afelioUA="3.343" periodoOrbitalD="2003.4" anoDescobrimento="1857" descobertoPor="Hermann Goldschmidt" /> 
    <asteroide id="a52"   nome="Europa"     diametrokm="301" perielioUA="2.785" afelioUA="3.417" periodoOrbitalD="1994.6" anoDescobrimento="1858" descobertoPor="Hermann Goldschmidt" /> 
    <asteroide id="a53"   nome="Kalypso"    diametrokm="115" perielioUA="2.086" afelioUA="3.154" periodoOrbitalD="1549"   anoDescobrimento="1858" descobertoPor="Robert Luther" />
    <asteroide id="a55"   nome="Pandora"    diametrokm="67"  perielioUA="2.359" afelioUA="3.158" periodoOrbitalD="1673"   anoDescobrimento="1858" descobertoPor="George Mary Searle" />
    <asteroide id="a65"   nome="Cibele"     diametrokm="273" perielioUA="3.073" afelioUA="3.794" periodoOrbitalD="2323.5" anoDescobrimento="1861" descobertoPor="Ernst Wilhelm Tempel" /> 
    <asteroide id="a87"   nome="Sylvia"     diametrokm="286" perielioUA="3.213" afelioUA="3.768" periodoOrbitalD="2381.7" anoDescobrimento="1866" descobertoPor="Norman Robert Pogson" /> 
    <asteroide id="a88"   nome="Tisbe"      diametrokm="232" perielioUA="2.312" afelioUA="3.224" periodoOrbitalD="1681.7" anoDescobrimento="1866" descobertoPor="Christian Peters" /> 
    <asteroide id="a94"   nome="Aurora"     diametrokm="197" perielioUA="2.883" afelioUA="3.435" periodoOrbitalD="2050.8" anoDescobrimento="1867" descobertoPor="James Craig Watson" /> 
    <asteroide id="a107"  nome="Camila"     diametrokm="215" perielioUA="3.204" afelioUA="3.750" periodoOrbitalD="2368.1" anoDescobrimento="1868" descobertoPor="Norman Robert Pogson"> 
        <satelite id="s2001.107.1" nome="S2001 107 1"  diametrokm="11"    raioMedOrbitakm="1235"  anoDescobrimento="2001" descobertoPor="A Storrs, F. Villas, R. Landis, E. Wells, C. Woods, B. Zellner, M. Gaffey" />
    </asteroide>
    <asteroide id="a121"  nome="Hermione"   diametrokm="190" perielioUA="2.98"  afelioUA="3.93"  periodoOrbitalD="2347.9" anoDescobrimento="1872" descobertoPor="James Craig Watson" >
        <satelite id="s121.1" nome="Lafayette"       diametrokm="13"    raioMedOrbitakm="-1"  anoDescobrimento="2002" descobertoPor="Keck II" />
    </asteroide> 
    <asteroide id="a140"  nome="Siwa"       diametrokm="110" perielioUA="2.141" afelioUA="3.324" periodoOrbitalD="1650" anoDescobrimento="1874" descobertoPor="Johann Palisa" />
    <asteroide id="a243"  nome="Ida"        diametrokm="45"  perielioUA="2.732" afelioUA="2.991" periodoOrbitalD="1768.1" anoDescobrimento="1884" descobertoPor="Johann Palisa" >
        <satelite id="s1994.243.1" nome="Dactil"       diametrokm="1.5"    raioMedOrbitakm="90"  anoDescobrimento="1994" descobertoPor="Galileo Project" />
    </asteroide> 
    <asteroide id="a253"  nome="Matilda"    diametrokm="16"  perielioUA="1.942" afelioUA="3.351" periodoOrbitalD="1572.8" anoDescobrimento="1885" descobertoPor="Johann Palisa" />
    <asteroide id="a324"  nome="Bamberga"   diametrokm="229" perielioUA="1.775" afelioUA="3.591" periodoOrbitalD="1605.4" anoDescobrimento="1892" descobertoPor="Johann Palisa" /> 
    <asteroide id="a375"  nome="Úrsula"     diametrokm="216" perielioUA="2.789" afelioUA="3.46"  periodoOrbitalD="2017.3" anoDescobrimento="1893" descobertoPor="Auguste Charlois" /> 
    <asteroide id="a423"  nome="Diotima"    diametrokm="209" perielioUA="2.941" afelioUA="3.191" periodoOrbitalD="1961"   anoDescobrimento="1896" descobertoPor="Auguste Charlois" /> 
    <asteroide id="a433"  nome="Eros"       diametrokm="12"  perielioUA="1.133" afelioUA="1.783" periodoOrbitalD="643.2"  anoDescobrimento="1898" descobertoPor="Carl Gustav Witt" /> 
    <asteroide id="a451"  nome="Patientia"  diametrokm="225" perielioUA="2.823" afelioUA="3.295" periodoOrbitalD="1954.2" anoDescobrimento="1899" descobertoPor="Auguste Charlois" /> 
    <asteroide id="a511"  nome="Davida"     diametrokm="289" perielioUA="2.58"  afelioUA="3.754" periodoOrbitalD="2058.4" anoDescobrimento="1903" descobertoPor="R. S. Dugan" /> 
    <asteroide id="a532"  nome="Herculina"  diametrokm="222" perielioUA="2.29"  afelioUA="3.26"  periodoOrbitalD="1687.5" anoDescobrimento="1904" descobertoPor="Max Wolf" /> 
    <asteroide id="a704"  nome="Interamnia" diametrokm="326" perielioUA="2.601" afelioUA="3.522" periodoOrbitalD="1957.5" anoDescobrimento="1910" descobertoPor="Vincenzo Cerulli" />  
</orbita>

=== helderdarocha/LearnXML/Exercicios_OLD/Parte_2_dtd/orbita_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orbita SYSTEM "orbita.dtd" >
<orbita raioMedUA="19.2">
    <planeta id="p7" nome="Urano" diametrokm="51118" anoDescobrimento="1781" perielioUA="18.3" afelioUA="20.1" periodoOrbitalD="30799" periodoRotacaoSideralH="17.24" inclinacaoAxial="97.77" massaKg="8.682e25" descobertoPor="William Herschel">
        <imagem href="uranus.jpg" />
        <satelite id="p7.1"  nome="Cordelia"   diametrokm="40"   raioMedOrbitakm="49751"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.2"  nome="Ofélia"     diametrokm="43"   raioMedOrbitakm="53764"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.3"  nome="Bianca"     diametrokm="51"   raioMedOrbitakm="59165"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.4"  nome="Créssida"   diametrokm="80"   raioMedOrbitakm="61766"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.5"  nome="Desdêmona"  diametrokm="64"   raioMedOrbitakm="62658"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.6"  nome="Julieta"    diametrokm="94"   raioMedOrbitakm="64360"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.7"  nome="Pórcia"     diametrokm="135"  raioMedOrbitakm="66097"    anoDescobrimento="1986" descobertoPor="Voyager 2" />
        <satelite id="p7.8"  nome="Rosalinda"  diametrokm="72"   raioMedOrbitakm="69927"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.22" nome="Cupido"     diametrokm="18"   raioMedOrbitakm="74800"    anoDescobrimento="2003" descobertoPor="Mark Showalter, Jack Lissauer" />
        <satelite id="p7.9"  nome="Belinda"    diametrokm="90"   raioMedOrbitakm="75255"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.10" nome="Perdita"    diametrokm="30"   raioMedOrbitakm="76420"    anoDescobrimento="1999" descobertoPor="Voyager 2" />    
        <satelite id="p7.11" nome="Puck"       diametrokm="162"  raioMedOrbitakm="86004"    anoDescobrimento="1986" descobertoPor="Voyager 2" />  
        <satelite id="p7.23" nome="Mab"        diametrokm="25"   raioMedOrbitakm="97734"    anoDescobrimento="2003" descobertoPor="Mark Showalter, Jack Lissauer" />
        <satelite id="p7.12" nome="Miranda"    diametrokm="472"  raioMedOrbitakm="129390"   anoDescobrimento="1948" descobertoPor="Gerard Kuiper" />    
        <satelite id="p7.13" nome="Ariel"      diametrokm="1158" raioMedOrbitakm="191020"   anoDescobrimento="1851" descobertoPor="William Lassell" />    
        <satelite id="p7.14" nome="Umbriel"    diametrokm="1169" raioMedOrbitakm="266300"   anoDescobrimento="1851" descobertoPor="William Lassell" />    
        <satelite id="p7.15" nome="Titânia"    diametrokm="1577" raioMedOrbitakm="435910"   massaKg="3.52e21" anoDescobrimento="1787" descobertoPor="William Herschel" >
            <imagem href="titania.jpg" />
        </satelite>
        <satelite id="p7.16" nome="Oberon"     diametrokm="1523" raioMedOrbitakm="583520"   massaKg="3.01e21" anoDescobrimento="1787" descobertoPor="William Herschel" >
            <imagem href="oberon.jpg" />
        </satelite>
        <satelite id="p7.24" nome="Francisco"  diametrokm="22"   raioMedOrbitakm="4276000"  anoDescobrimento="2003" descobertoPor="Matthew Holman et al" /> 
        <satelite id="p7.17" nome="Calibã"     diametrokm="72"   raioMedOrbitakm="7231000"  anoDescobrimento="1997" descobertoPor="Brett Gladman et al" />    
        <satelite id="p7.18" nome="Estéfano"   diametrokm="32"   raioMedOrbitakm="8004000"  anoDescobrimento="1999" descobertoPor="Brett Gladman et al" />    
        <satelite id="p7.25" nome="Trínculo"   diametrokm="18"   raioMedOrbitakm="8504000"  anoDescobrimento="2001" descobertoPor="Matthew Holman et al" />
        <satelite id="p7.19" nome="Sicorax"    diametrokm="150"  raioMedOrbitakm="12179000" anoDescobrimento="1997" descobertoPor="Seth Barnes Nicholson et al" />    
        <satelite id="p7.26" nome="Margarete"  diametrokm="20"   raioMedOrbitakm="14345000" anoDescobrimento="2003" descobertoPor="Scott Sheppard, David Jewitt" />
        <satelite id="p7.20" nome="Próspero"   diametrokm="50"   raioMedOrbitakm="16256000" anoDescobrimento="1999" descobertoPor="Matthew Holman et al" />    
        <satelite id="p7.21" nome="Setebos"    diametrokm="48"   raioMedOrbitakm="17418000" anoDescobrimento="1999" descobertoPor="John Kavelaars et al" />    
        <satelite id="p7.27" nome="Ferdinando" diametrokm="20"   raioMedOrbitakm="20901000" anoDescobrimento="2003" descobertoPor="Matthew Holman et al" />
    </planeta>
</orbita>
