=== helderdarocha/LearnXML/Exemplos_Cap_4_XSD/sol_2001_schema_ns_solucao/com_ns/sistemaEstelar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.3 (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cosmos.org.br" targetNamespace="http://www.cosmos.org.br" xmlns:st="http://www.cosmos.org.br/satelites" xmlns:cm="http://www.cosmos.org.br/cometas" elementFormDefault="qualified">
	<xs:import namespace="http://www.cosmos.org.br/satelites" schemaLocation="satelites.xsd"/>
	<xs:import namespace="http://www.cosmos.org.br/cometas" schemaLocation="cometas.xsd"/>
	<xs:complexType name="centroType">
		<xs:sequence>
			<xs:element name="estrela" type="estrelaType"/>
			<xs:element ref="st:imagem" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="estrelaType">
		<xs:complexContent>
			<xs:extension base="st:astroType">
				<xs:sequence>
					<xs:element name="satelite" type="st:sateliteType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="cor" type="xs:token"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="orbitaType">
		<xs:choice>
			<xs:element name="estrela" type="estrelaType"/>
			<xs:element name="planeta" type="st:sateliteType"/>
			<xs:element name="asteroide" type="st:sateliteType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="raioMedUA" type="xs:decimal"/>
	</xs:complexType>
	<xs:element name="sistemaEstelar">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="centro" type="centroType"/>
				<xs:element name="orbita" type="orbitaType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="cm:cometa" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== helderdarocha/LearnXML/Exemplos_Cap_4_XSD/sol_2001_schema_ns_solucao/com_ns/sol_ns.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<se:sistemaEstelar xmlns:se="http://www.cosmos.org.br" xmlns:sat="http://www.cosmos.org.br/satelites" xmlns:cmt="http://www.cosmos.org.br/cometas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cosmos.org.br 		  sistemaEstelar.xsd
                                       http://www.cosmos.org.br/satelites satelites.xsd
                                       http://www.cosmos.org.br/cometas   cometas.xsd">
	<se:centro>
		<se:estrela id="x0" nome="Sol" diametrokm="1390000" cor="amarela"/>
		<sat:imagem href="sun.gif"/>
	</se:centro>
	<se:orbita raioMedUA="0.387">
		<se:planeta id="p1" nome="Mercúrio" diametrokm="4879">
			<sat:imagem href="mercury.jpg"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="0.723">
		<se:planeta id="p2" nome="Venus" diametrokm="12104">
			<sat:imagem href="venus.jpg"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="1">
		<se:planeta id="p3" nome="Terra" diametrokm="12756">
			<sat:imagem href="earth.jpg"/>
			<sat:satelite id="p3.1" nome="Lua" diametrokm="3475" raioMedOrbitakm="384400"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="1.52">
		<se:planeta id="p4" nome="Marte" diametrokm="6794">
			<sat:imagem href="mars.jpg"/>
			<sat:satelite id="p4.1" nome="Phobos" diametrokm="11.2" raioMedOrbitakm="9380" anoDescobrimento="1877"/>
			<sat:satelite id="p4.2" nome="Deimos" diametrokm="6.4" raioMedOrbitakm="23460" anoDescobrimento="1877"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="2.75">
		<se:asteroide id="a1" nome="Ceres" diametrokm="932" anoDescobrimento="1801"/>
		<se:asteroide id="a5" nome="Davida" diametrokm="336" anoDescobrimento="1903"/>
		<se:asteroide id="a13" nome="Eros" diametrokm="12" anoDescobrimento="1893"/>
		<se:asteroide id="a8" nome="Eunomia" diametrokm="272" anoDescobrimento="1851"/>
		<se:asteroide id="a7" nome="Europa" diametrokm="312" anoDescobrimento="1858"/>
		<se:asteroide id="a12" nome="Gaspra" diametrokm="13" anoDescobrimento="1916"/>
		<se:asteroide id="a4" nome="Hygiea" diametrokm="430" anoDescobrimento="1849"/>
		<se:asteroide id="a10" nome="Ida" diametrokm="45" anoDescobrimento="1884"/>
		<se:asteroide id="a6" nome="Interamnia" diametrokm="334" anoDescobrimento="1910"/>
		<se:asteroide id="a11" nome="Matilda" diametrokm="16" anoDescobrimento="1885"/>
		<se:asteroide id="a3" nome="Pallas" diametrokm="522" anoDescobrimento="1802"/>
		<se:asteroide id="a9" nome="Psique" diametrokm="264" anoDescobrimento="1852"/>
		<se:asteroide id="a14" nome="Sylvia" diametrokm="272" anoDescobrimento="1866"/>
		<se:asteroide id="a2" nome="Vesta" diametrokm="524" anoDescobrimento="1807"/>
	</se:orbita>
	<se:orbita raioMedUA="5.2">
		<se:planeta id="p5" nome="Júpiter" diametrokm="142984">
			<sat:imagem href="jupiter.jpg"/>
			<sat:satelite id="p5.1" nome="Métis" diametrokm="40" raioMedOrbitakm="127969" anoDescobrimento="1979"/>
			<sat:satelite id="p5.2" nome="Adrastéa" diametrokm="11" raioMedOrbitakm="128971" anoDescobrimento="1979"/>
			<sat:satelite id="p5.3" nome="Amaltéa" diametrokm="110" raioMedOrbitakm="181300" anoDescobrimento="1892"/>
			<sat:satelite id="p5.4" nome="Tebas" diametrokm="50" raioMedOrbitakm="221895" anoDescobrimento="1979"/>
			<sat:satelite id="p5.5" nome="Io" diametrokm="3630" raioMedOrbitakm="421600" anoDescobrimento="1610"/>
			<sat:satelite id="p5.6" nome="Europa" diametrokm="3138" raioMedOrbitakm="670900" anoDescobrimento="1610"/>
			<sat:satelite id="p5.7" nome="Ganimede" diametrokm="5262" raioMedOrbitakm="1070000" anoDescobrimento="1610"/>
			<sat:satelite id="p5.8" nome="Callisto" diametrokm="4800" raioMedOrbitakm="1883000" anoDescobrimento="1610"/>
			<sat:satelite id="p5.9" nome="S/1975" diametrokm="8" raioMedOrbitakm="7435000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.10" nome="Leda" diametrokm="16" raioMedOrbitakm="11094000" anoDescobrimento="1974"/>
			<sat:satelite id="p5.11" nome="Himalia" diametrokm="186" raioMedOrbitakm="11480000" anoDescobrimento="1904"/>
			<sat:satelite id="p5.12" nome="Lysithea" diametrokm="36" raioMedOrbitakm="11720000" anoDescobrimento="1938"/>
			<sat:satelite id="p5.13" nome="Elara" diametrokm="76" raioMedOrbitakm="11737000" anoDescobrimento="1905"/>
			<sat:satelite id="p5.14" nome="S/2000" diametrokm="4" raioMedOrbitakm="12654000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.15" nome="S/2000" diametrokm="4" raioMedOrbitakm="20375000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.16" nome="S/2000" diametrokm="5" raioMedOrbitakm="20733000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.17" nome="S/2000" diametrokm="4" raioMedOrbitakm="21019000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.18" nome="S/2000" diametrokm="7" raioMedOrbitakm="21162000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.19" nome="Ananke" diametrokm="30" raioMedOrbitakm="21200000" anoDescobrimento="1951"/>
			<sat:satelite id="p5.20" nome="S/2000" diametrokm="5" raioMedOrbitakm="21734000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.21" nome="S/2000" diametrokm="3" raioMedOrbitakm="21948000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.22" nome="Carme" diametrokm="40" raioMedOrbitakm="22600000" anoDescobrimento="1938"/>
			<sat:satelite id="p5.23" nome="S/2000" diametrokm="4" raioMedOrbitakm="22806000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.24" nome="Pasiphae" diametrokm="50" raioMedOrbitakm="23500000" anoDescobrimento="1908"/>
			<sat:satelite id="p5.25" nome="S/2000" diametrokm="5" raioMedOrbitakm="23521000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.26" nome="Sinope" diametrokm="32" raioMedOrbitakm="23700000" anoDescobrimento="1914"/>
			<sat:satelite id="p5.27" nome="S/2000" diametrokm="5" raioMedOrbitakm="24164000" anoDescobrimento="2000"/>
			<sat:satelite id="p5.28" nome="S/1999" diametrokm="5" raioMedOrbitakm="24296000" anoDescobrimento="1999"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="9.54">
		<se:planeta id="p6" nome="Saturno" diametrokm="120536">
			<sat:imagem href="saturn.jpg"/>
			<sat:satelite id="p6.1" nome="Pan" diametrokm="10" raioMedOrbitakm="133583" anoDescobrimento="1990"/>
			<sat:satelite id="p6.2" nome="Atlas" diametrokm="36" raioMedOrbitakm="137640" anoDescobrimento="1980"/>
			<sat:satelite id="p6.3" nome="Prometeu" diametrokm="120" raioMedOrbitakm="139350" anoDescobrimento="1980"/>
			<sat:satelite id="p6.4" nome="Pandora" diametrokm="100" raioMedOrbitakm="141700" anoDescobrimento="1980"/>
			<sat:satelite id="p6.5" nome="Epimeteu" diametrokm="120" raioMedOrbitakm="151422" anoDescobrimento="1966"/>
			<sat:satelite id="p6.6" nome="Janus" diametrokm="190" raioMedOrbitakm="151472" anoDescobrimento="1966"/>
			<sat:satelite id="p6.7" nome="Mimas" diametrokm="392" raioMedOrbitakm="185520" anoDescobrimento="1789"/>
			<sat:satelite id="p6.8" nome="Encelado" diametrokm="500" raioMedOrbitakm="238020" anoDescobrimento="1789"/>
			<sat:satelite id="p6.9" nome="Tétis" diametrokm="1060" raioMedOrbitakm="294660" anoDescobrimento="1684"/>
			<sat:satelite id="p6.10" nome="Telesto" diametrokm="30" raioMedOrbitakm="294660" anoDescobrimento="1980"/>
			<sat:satelite id="p6.11" nome="Calipso" diametrokm="28" raioMedOrbitakm="294660" anoDescobrimento="1980"/>
			<sat:satelite id="p6.12" nome="Dione" diametrokm="1120" raioMedOrbitakm="377400" anoDescobrimento="1684"/>
			<sat:satelite id="p6.13" nome="Helena" diametrokm="34" raioMedOrbitakm="377400" anoDescobrimento="1980"/>
			<sat:satelite id="p6.14" nome="Rhea" diametrokm="1530" raioMedOrbitakm="527040" anoDescobrimento="1672"/>
			<sat:satelite id="p6.15" nome="Titã" diametrokm="5150" raioMedOrbitakm="1221850" anoDescobrimento="1655"/>
			<sat:satelite id="p6.16" nome="Hiperion" diametrokm="300" raioMedOrbitakm="1481000" anoDescobrimento="1848"/>
			<sat:satelite id="p6.17" nome="Iapetus" diametrokm="1460" raioMedOrbitakm="3561300" anoDescobrimento="1671"/>
			<sat:satelite id="p6.18" nome="Phoebe" diametrokm="220" raioMedOrbitakm="12952000" anoDescobrimento="1898"/>
			<sat:satelite id="p6.19" nome="S/2000" diametrokm="14" raioMedOrbitakm="11365000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.20" nome="S/2000" diametrokm="10" raioMedOrbitakm="11440000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.21" nome="S/2000" diametrokm="19" raioMedOrbitakm="15199000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.22" nome="S/2000" diametrokm="6" raioMedOrbitakm="15645000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.23" nome="S/2000" diametrokm="26" raioMedOrbitakm="16392000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.24" nome="S/2000" diametrokm="9" raioMedOrbitakm="17611000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.25" nome="S/2000" diametrokm="32" raioMedOrbitakm="18160000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.26" nome="S/2000" diametrokm="13" raioMedOrbitakm="18239000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.27" nome="S/2000" diametrokm="6" raioMedOrbitakm="18709000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.28" nome="S/2000" diametrokm="6" raioMedOrbitakm="19470000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.29" nome="S/2000" diametrokm="6" raioMedOrbitakm="20470000" anoDescobrimento="2000"/>
			<sat:satelite id="p6.30" nome="S/2000" diametrokm="16" raioMedOrbitakm="23096000" anoDescobrimento="2000"/>
		</se:planeta>
	</se:orbita>
	<se:orbita raioMedUA="19.2">
		<se:planeta id="p7" nome="Urano" diametrokm="51118" anoDescobrimento="1781">
			<sat:imagem href="uranus.jpg"/>
			<sat:satelite id="p7.1" nome="Cordelia" diametrokm="26" raioMedOrbitakm="49750" anoDescobrimento="1986"/>
			<sat:satelite id="p7.2" nome="Ofélia" diametrokm="32" raioMedOrbitakm="53760" anoDescobrimento="1986"/>
			<sat:satelite id="p7.3" nome="Bianca" diametrokm="44" raioMedOrbitakm="59160" anoDescobrimento="1986"/>
