=== helderdarocha/LearnXML/WorkspaceAula/letter.xsd
<?xml version="1.0" encoding="iso-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="carta"
            xmlns="carta">
   <xsd:element name="letter" type="letterType" />
   <xsd:complexType name="letterType">
    <xsd:sequence>
      <xsd:element ref="contact" maxOccurs="2" minOccurs="2" />
      <xsd:element ref="salutation"/>
      <xsd:element ref="paragraph" maxOccurs="unbounded" minOccurs="1" />
      <xsd:element ref="closing"/>
      <xsd:element ref="signature"/>
    </xsd:sequence>
   </xsd:complexType>
   
   <xsd:element name="contact" type="contactType" />
   <xsd:complexType name="contactType">
    <xsd:sequence>
      <xsd:element ref="name"/>
      <xsd:element ref="address1"/>
      <xsd:element ref="address2"/>
      <xsd:element ref="city"/>
      <xsd:element ref="state"/>
      <xsd:element ref="zip"/>
      <xsd:element ref="phone"/>
      <xsd:element ref="flag"/>
    </xsd:sequence>
    <xsd:attribute ref="type" use="required"/>
   </xsd:complexType>
   
   <xsd:element name="name" type="xsd:string" />
   <xsd:element name="address1" type="xsd:string" />
   <xsd:element name="address2" type="xsd:string" />
   <xsd:element name="city" type="xsd:string" />
   <xsd:element name="salutation" type="xsd:string" />
   <xsd:element name="bold" type="xsd:string" />
   <xsd:element name="closing" type="xsd:string" />
   <xsd:element name="signature" type="xsd:string" />
   
   <xsd:element name="state">
     <xsd:simpleType>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="DF"/>
            <xsd:enumeration value="SP"/>
            <xsd:enumeration value="RJ"/>
            <xsd:enumeration value="PA"/>
            <xsd:enumeration value="BA"/>
            <xsd:enumeration value="RS"/>
            <xsd:enumeration value="PB"/>
            <xsd:enumeration value="CE"/>
            <xsd:enumeration value="SC"/>
            <xsd:enumeration value="AM"/>
        </xsd:restriction>
     </xsd:simpleType>
   </xsd:element>
   
   <xsd:element name="zip">
      <xsd:simpleType>
        <xsd:restriction base="xsd:integer">
            <xsd:length value="5"/>
        </xsd:restriction>
      </xsd:simpleType>
   </xsd:element>
   
   <xsd:element name="phone">
     <xsd:simpleType>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{4}-[0-9]{4}"/>
        </xsd:restriction>
      </xsd:simpleType>
   </xsd:element>
   
   <xsd:element name="flag">
    <xsd:complexType>
     <xsd:attribute ref="gender"/>
    </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="paragraph">
    <xsd:complexType mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="bold"/>
        </xsd:choice>
    </xsd:complexType>
   </xsd:element>

   <xsd:attribute name="type">
      <xsd:simpleType>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="to"/>
            <xsd:enumeration value="from"/>
        </xsd:restriction>
      </xsd:simpleType>
   </xsd:attribute>
   
   <xsd:attribute name="gender">
      <xsd:simpleType>
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:pattern value="(M|F)" />
        </xsd:restriction>
      </xsd:simpleType>
   </xsd:attribute>
</xsd:schema>

=== helderdarocha/LearnXML/WorkspaceAula/letter.xml
<?xml version = "1.0"?>
<letter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="carta letter.xsd"
        xmlns="carta">
   <contact type = "from">
      <name>Jane Doe</name>
      <address1>Box 12345</address1>
      <address2>15 Any Ave.</address2>
      <city>Othertown</city>
      <state>SP</state>
      <zip>67890</zip>
      <phone>4555-4321</phone>
      <flag gender = "F"/>
   </contact>
   <contact type = "to">
      <name>Jane Doe</name>
      <address1>123 Main St.</address1>
      <address2></address2>
      <city>Anytown</city>
      <state>RJ</state>
      <zip>12345</zip>
      <phone>4555-1234</phone>
      <flag gender = "M"/>
   </contact>

   <salutation>Dear Sir:</salutation>

   <paragraph>It is our privilege to inform you about our new
      database managed with <bold>XML</bold>. This system
      allows you to reduce the load on your inventory list
      server by having the client machine perform the work of
      sorting and filtering the data.</paragraph>

   <paragraph>The data in an XML element is normalized, so
      plain-text diagrams such as
         /---\
         |   |
         \---/
      will become gibberish.</paragraph>

    <closing>Sincerely</closing>
    <signature>Ms. Doe</signature>

</letter>

<!-- 
 **************************************************************************
 * (C) Copyright 2001 by Deitel & Associates, Inc. and Prentice Hall.     *
 * All Rights Reserved.                                                   *
 *                                                                        *
 * DISCLAIMER: The authors and publisher of this book have used their     *
 * best efforts in preparing the book. These efforts include the          *
 * development, research, and testing of the theories and programs        *
 * to determine their effectiveness. The authors and publisher make       *
 * no warranty of any kind, expressed or implied, with regard to these    *
 * programs or to the documentation contained in these books. The authors *
 * and publisher shall not be liable in any event for incidental or       *
 * consequential damages in connection with, or arising out of, the       *
 * furnishing, performance, or use of these programs.                     *
 **************************************************************************
-->
