<!DOCTYPE item [
    <!ELEMENT item (b|c|d)*>
    <!ELEMENT a ANY>
    <!ELEMENT b ANY>
    <!ELEMENT c ANY>
    <!ELEMENT d ANY>
    <!ELEMENT e ANY>
    <!ELEMENT f ANY>
    <!ELEMENT g ANY>
]>

<item>
    <b></b>
    <b></b>
    <b></b>
    <c></c><b></b>
</item>

